---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/shared/common/requirements.yml

lint: |
  set -e
  yamllint . --strict
  ansible-lint

driver:
  name: docker

platforms:
  - name: ansible-gitlab-runner-ubuntu
    image: docker.io/pycontribs/ubuntu
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

provisioner:
  name: ansible
  playbooks:
    prepare: ../shared/docker/prepare.yml
    converge: ../shared/docker/converge.yml

verifier:
  name: ansible
