---
- name: Prepare
  hosts: all
  become: true

  vars:
    molecule_docker_environment: true

  roles:
    - role: install-docker
      storage_driver: overlay2
      cleanup_enabled: false
      install_pip_docker: true
