---
- name: Check 'gitlab_runner_config_volume' parameter
  assert:
    that:
      - "gitlab_runner_config_volume is defined"
      - "gitlab_runner_config_volume | length > 0"
    fail_msg: "parameter 'gitlab_runner_config_volume' is missing"

- name: Check 'gitlab_runner_gitlab_uri' parameter
  assert:
    that:
      - "gitlab_runner_gitlab_uri is defined"
      - "gitlab_runner_gitlab_uri | length > 0"
    fail_msg: "parameter 'gitlab_runner_gitlab_uri' is missing"

- name: Check 'gitlab_runner_registration_token' parameter
  assert:
    that:
      - "gitlab_runner_registration_token is defined"
      - "gitlab_runner_registration_token | length > 0"
    fail_msg: "parameter 'gitlab_runner_registration_token' is missing"
