---
- include: check-parameters.yml

- name: pull image
  docker_image:
    name: "{{ image_name }}:{{ image_version }}"
    source: pull

- include: register_runner.yml
  when: not (disable_register | bool)

- name: Setup systemd service name
  set_fact:
    runner_service_name: "gitlab-runner-{{ runner_name }}"
  when: runner_name is defined
    and runner_name | length > 0

- name: Setup systemd service name
  set_fact:
    runner_service_name: gitlab-runner
  when: runner_name is not defined
    or runner_name | length < 1

- name: Create gitlab-runner systemd unit file
  template:
    src: gitlab-runner.systemd.j2
    dest: "/etc/systemd/system/{{ runner_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart gitlab-runner service

- name: Enable service
  service:
    name: "{{ runner_service_name }}"
    enabled: true
  register: runner_service_state
  changed_when: runner_service_state.status.SubState != 'running'
  notify: Start gitlab-runner service

- name: Flush handlers
  meta: flush_handlers
