---
- include: check-parameters.yml

- name: pull image
  docker_image:
    name: "{{ gitlab_runner_image_name }}:{{ gitlab_runner_image_version }}"
    source: pull
  notify: Restart gitlab-runner service

- include: register_runner.yml
  when: not (gitlab_runner_disable_register | bool)

- name: Setup systemd service name
  set_fact:
    runner_service_name: "gitlab-runner-{{ gitlab_runner_runner_name }}"
  when: gitlab_runner_runner_name is defined
    and gitlab_runner_runner_name | length > 0

- name: Setup systemd service name
  set_fact:
    runner_service_name: gitlab-runner
  when: gitlab_runner_runner_name is not defined
    or gitlab_runner_runner_name | length < 1

- name: Create gitlab-runner systemd unit file
  template:
    src: gitlab-runner.systemd.j2
    dest: "/etc/systemd/system/{{ runner_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart gitlab-runner service

- name: Reload gitlab-runner service if necessary
  meta: flush_handlers

- name: Enable gitlab-runner service
  service:
    name: "{{ runner_service_name }}"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
