---
- include: check-parameters.yml

- name: pull image
  docker_image:
    name: "{{image_name}}:{{image_version}}"
    source: pull

- include: register_runner.yml
  when: disable_register | bool == False

- name: Setup systemd service name
  set_fact:
    runner_service_name: "{{ 'gitlab-runner-{{runner_name}}' if runner_name != '' else 'gitlab-runner' }}"

- name: Create gitlab-runner systemd unit file
  template:
    src: gitlab-runner.systemd.j2
    dest: "/etc/systemd/system/{{runner_service_name}}.service"
    owner: root
    group: root
    mode: 0644
  register: gitlab_runner_service

- name: Reload systemd
  command: systemctl daemon-reload
  when: gitlab_runner_service.changed

- name: Restart service
  service:
    name: "{{runner_service_name}}"
    state: restarted
    enabled: yes
  when: gitlab_runner_service.changed
    or runner_register is defined
    and runner_register.changed

- name: Start service (if not running)
  service:
    name: "{{runner_service_name}}"
    state: started
    enabled: yes
