---
- include: check-parameters.yml

- name: pull image
  docker_image:
    name: "{{ image_name }}:{{ image_version }}"
    source: pull
  notify: Restart gitlab-runner service

- include: register_runner.yml
  when: not (disable_register | bool)

- name: Setup systemd service name
  set_fact:
    runner_service_name: "gitlab-runner-{{ runner_name }}"
  when: runner_name is defined
    and runner_name | length > 0

- name: Setup systemd service name
  set_fact:
    runner_service_name: gitlab-runner
  when: runner_name is not defined
    or runner_name | length < 1

- name: Create gitlab-runner systemd unit file
  template:
    src: gitlab-runner.systemd.j2
    dest: "/etc/systemd/system/{{ runner_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart gitlab-runner service

- name: Reload gitlab-runner service if necessary
  meta: flush_handlers

- name: Enable gitlab-runner service
  service:
    name: "{{ runner_service_name }}"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
