---
- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Start gitlab-runner service
  service:
    name: "{{ runner_service_name }}"
    state: started
  register: gitlab_runner_service_start

- name: Restart gitlab-runner service
  service:
    name: "{{ runner_service_name }}"
    state: restarted
  when: not (
    gitlab_runner_service_start is defined
    and gitlab_runner_service_start.changed
    )
