---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-gitlab-runner
      gitlab_runner_image_version: alpine-v12.9.0
      gitlab_runner_gitlab_uri: http://my.gitlab.server.org
      gitlab_runner_registration_token: YydxtxYTUFgYsWxavDvv
      gitlab_runner_description: my-runner
      gitlab_runner_config_volume: /srv/gitlab-runner
      gitlab_runner_disable_register: true
      gitlab_runner_refresh_register: false
